### ISSUE TITLE
Common: missing reset command

### ISSUE THREAD

**Issue by vkottler** [madison-embedded/gcc-builds#11]
Being able to reset the board from the command line would be a great utility.

**Comment by vkottler** [comment]
I recommend cloning [this repo](https://github.com/madison-embedded/documentation) to get all of the necessary documentation.

The [STM32F767ZI reference manual](https://github.com/madison-embedded/documentation/blob/master/stm32/f7xx/RM.pdf) says the following:

![image](https://user-images.githubusercontent.com/15205052/27414522-8441793c-56c7-11e7-98f3-1e774fac875c.png)

When we consult the [ARM Cortex-M7 Reference Manual](https://github.com/madison-embedded/documentation/blob/master/ARM/cortex_m7.pdf) as instructed, surprise! There's no description for the "Application Interrupt and Reset Control Register".

When we search it [online here](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0646a/Cihehdge.html) we can actually read about it:

![image](https://user-images.githubusercontent.com/15205052/27414653-4dde9946-56c8-11e7-864c-e1ee16d39a29.png)

hmm... yeah I'm sure it's somewhere in these manuals!

**Comment by davidguyuchen** [comment]
It seems we can take advantage of NVIC_SYSTEMRESET command documented in core_cm7.h file in the CMSIS files folder. It basically overwrites the reset register bits to implement a software reset, which is pretty much what we are looking for.

<img width="1021" alt="screen shot 2017-06-26 at 2 54 11 pm" src="https://user-images.githubusercontent.com/14173586/27557757-50f1c9ee-5a80-11e7-880e-b84e2a81500b.png">

**Comment by vkottler** [comment]
Oh dang, good find. There's always useful stuff in there! Feel free to make a command-line command that calls it and test it out

**Comment by davidguyuchen** [comment]
Has been implemented and pushed.
