### ISSUE TITLE
STM32 Nucleo 144 F767ZI: Missing ADC Driver

### ISSUE THREAD

**Issue by vkottler** [madison-embedded/gcc-builds#15]
Needed for pressure sensor readings and thermistors.

**Comment by vkottler** [comment]
![image](https://user-images.githubusercontent.com/15205052/27599783-6ff60de6-5b2f-11e7-8b5c-2affd2e078d8.png)

Datasheet:
![image](https://user-images.githubusercontent.com/15205052/27599865-ad206f36-5b2f-11e7-813b-12eb30b91f9e.png)
![image](https://user-images.githubusercontent.com/15205052/27599907-da125d6a-5b2f-11e7-8229-743395c2277d.png)
![image](https://user-images.githubusercontent.com/15205052/27599958-f400117c-5b2f-11e7-95c4-3239e2ca1a19.png)

**Comment by vkottler** [comment]
needs refactoring but is essentially done

**Comment by vkottler** [comment]
Remember to change 6 bit accuracy, finish `ar` command

**Comment by vkottler** [comment]
thermistor code from pod 1: [https://github.com/vkottler/badgerloopControls/blob/master/Pic32/peripherals/C/thermistor.c](https://github.com/vkottler/badgerloopControls/blob/master/Pic32/peripherals/C/thermistor.c)

**Comment by csgreen3** [comment]
can read and write to all adc ar prints out all ar alias or ar port pin will print out a specific one
