### ISSUE TITLE
Common: Missing float command

### ISSUE THREAD

**Issue by vkottler** [madison-embedded/gcc-builds#19]
Different ARM cores have varying levels of hardware / dedicated FPU support.

We need a float command that implements the following argument pattern:

`float [ add | subtract | multiply | divide | + | - | * | / ] <arg1> <arg2>`

In addition to performing the calculation, it would be great to have some diagnostic information about how the operation was carried out, including amount of time / number of instructions required if possible.

**Comment by vkottler** [comment]
Best if done before next weekend (:

**Comment by vkottler** [comment]
Can you build this in Keil uVision IDE and compare performance?

**Comment by davidguyuchen** [comment]
Yep, I will give it a try and I'm assuming we are still using the C standard library?

**Comment by vkottler** [comment]
Yeah, there's a different way to go about re-targeting `printf` in Keil though
