### ISSUE TITLE
STM32 Nucleo 144 F767ZI: Missing EXTI Driver 

### ISSUE THREAD

**Issue by csgreen3** [madison-embedded/gcc-builds#24]
Connect interrupt handlers to the GPIO pins. In handler we need to save the 2 most recent time stamps ie: 
prev = curr; 
curr = getCurrentTimestamp();

testing can be done with the retro reflective sensors

**Comment by csgreen3** [comment]
Functioning just needs to determine how we want to return

**Comment by vkottler** [comment]
This is potentially replaced by input capture mode on a timer channel

**Comment by vkottler** [comment]
Would you call the driver done then?

**Comment by csgreen3** [comment]
I will be working on making a command for this. Probably to just ready the current and previous time stamp or what ever we want to have saved in the handler.

**Comment by csgreen3** [comment]
Can take in a alias or pin number
