### ISSUE TITLE
Common: Missing a command for toggling pins

### ISSUE THREAD

**Issue by vkottler** [madison-embedded/gcc-builds#8]
This may be the single most useful command-line utility we can provide.

Something like `pin [<pin_num> | <PORT><PIN>] [on | off]` would work best where `pin_num` is a pin from the female headers and `<PORT><PIN>` is something like **A8** or **C5** (may also be routed to one of the female header pins).

Eventually we'll want to support aliases for pins such as braking_solenoid_X so a struct that also implements that capability would be ideal.

**Comment by vkottler** [comment]
STM32 Nucleo 144 related: [I/O schematic](https://github.com/madison-embedded/documentation/blob/master/stm32/nucleo/ioSch.PNG), [Badgerloop I/O documentation](https://docs.google.com/spreadsheets/d/1tzqCBdWPqIOUyLG5kfgT8CnwwVi2Sx8zOyC4Jp1TQsU/edit?usp=sharing)

**Comment by vkottler** [comment]
It might be better to support read and write, in the future we'll also need an analog read function.

**Comment by vkottler** [comment]
Want to make sure to check if a pin is already enabled and serving as an alternate function pin

**Comment by vkottler** [comment]
add info to: `pin [<pin_num> | <PORT><PIN>] [on | off | info]`

Come up with a way to print info for all pins or all pins from a certain port.

**Comment by csgreen3** [comment]
Besides alternate functions and analog information this is completed

**Comment by vkottler** [comment]
Have `pin <PORT> [info]` display any potential alias of each pin in parentheses at the end

**Comment by csgreen3** [comment]
![image](https://user-images.githubusercontent.com/16278441/27721070-9bcd2634-5d23-11e7-9950-ee65d7c41997.png)

**Comment by vkottler** [comment]
Make the boolean flag mean the alias should not be used to initialize the pin, allow user to have full contorl over aliased pins

**Comment by csgreen3** [comment]
added initialization
